# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, verbose_name='организация')),
                ('link', models.URLField(max_length=90, verbose_name='ссылка на сайт')),
                ('about_the_organization', models.TextField(verbose_name='коротко о компании')),
                ('label', models.CharField(max_length=32, verbose_name='путь до картинки')),
            ],
        ),
        migrations.CreateModel(
            name='MyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.PositiveIntegerField(verbose_name='ID компании из CompanyName')),
                ('links', models.CharField(max_length=32, verbose_name='ссылка на сайт')),
                ('my_duties', models.TextField(verbose_name='должностные обязательства')),
                ('periods', models.PositiveIntegerField(default=1, verbose_name='период работы')),
            ],
        ),
    ]
