# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.CompanyName', verbose_name='ID компании из CompanyName'),
        ),
    ]
